import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const proof='.flowkit/artifacts/20260908-05-lightweight-workflow-management/changes/correct-project-onboarding-and-agent-entry/proof/20260911-067-apply';
const root='openspec/changes/correct-project-onboarding-and-agent-entry',manager='.tmp/onboarding-039-manager/node_modules/flowkit-next';
const ref=p=>{const b=fs.readFileSync(p);return {path:p,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')};};
const read=p=>JSON.parse(fs.readFileSync(p));
const pre=read(proof+'/preflight.json');
const manifest='openspec/delivery-groups/20260908-05-lightweight-workflow-management.yaml';
const before=pre.inputs.find(r=>r.path===manifest);
const current=fs.readFileSync(manifest,'utf8');
const lines=current.split(/(?<=\n)/),notes=lines.filter(l=>l.startsWith('  planningHistoryNote:'));
assert.equal(notes.length,1);
const restored=Buffer.from(lines.filter(l=>!l.startsWith('  planningHistoryNote:')).join(''));
assert.equal(restored.length,before.bytes);assert.equal(createHash('sha256').update(restored).digest('hex'),before.sha256);
for(const r of read(pre.acceptedReview.path).artifacts.filter(r=>!r.path.endsWith('/tasks.md')))assert.deepEqual(ref(r.path),r);
for(const r of read(proof+'/removal-sources.json').refs)assert(!fs.existsSync(r.path));
for(const relative of ['README.md','docs/onboarding.md'])assert(fs.readFileSync(manager+'/'+relative).equals(fs.readFileSync(relative)));
const installed=read(manager+'/package.json'),source=read('package.json');
for(const key of ['name','version','bin','dependencies','files','engines'])assert.deepEqual(installed[key],source[key]);
assert.equal(ref('pnpm-lock.yaml').sha256,pre.inputs.find(r=>r.path==='pnpm-lock.yaml').sha256);
const report={checkedAt:new Date().toISOString(),finalPackage:ref('.tmp/onboarding-039-pack-final/flowkit-next-0.1.0.tgz'),installedDocumentationEqual:true,manifestOnlyAddedHistoryNote:true,approvedPlanningUnchangedExceptTaskProgress:true,dependencyLockUnchanged:true,exactRemovals:read(proof+'/removal-sources.json').refs,artifacts:['README.md','docs/onboarding.md','package.json','tests/unit/domain/project-onboarding.test.ts',manifest].map(ref),scope:'no src/Skill changes; exact three deletions recoverable from Git; original D05 reference and facts remain',acceptance:{fixedInstallation:'passed',powershellDoctorAndIdleQuery:'passed',realAuthorWork:'not-executed: awaiting explicit first ordinal initialization',actualNewAgentSession:'not-executed'}};
fs.writeFileSync(proof+'/implementation-audit.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify(report));
