import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {gitBytes} from '../src/internal/git-checkpoint-scope.ts';
import {readCandidateRunChain} from '../src/internal/git-index-run-chain.ts';
import {requireNewManagedEvidenceBytes} from '../src/internal/managed-evidence-checkpoint.ts';
import {executeScopedCheckpoint} from '../src/internal/git-checkpoint-execution.ts';
const root=await fs.mkdtemp(path.join(process.cwd(),'.tmp/reviewer054-drift-'));
const deliveryId='delivery-one',changeId='change-one',runId='20261001-001-explore';
const base=`.flowkit/runs/${deliveryId}/001-${changeId}/${runId}`,proofPath=`.flowkit/artifacts/${deliveryId}/changes/${changeId}/proof/${runId}/proof.txt`;
const bytes=Buffer.from('fixture proof\r\n'),identity={deliveryId,changeId,actionId:'explore'};
const context={runId,occurrence:{date:'20261001',sequence:1,actionId:'explore'},actionIdentity:identity,role:'author',lifecycleState:'prepared',ownerAuthority:null,previousRunId:null};
const result={runId,actionIdentity:identity,authorConclusion:null,reviewerVerdict:null,verificationVerdict:null,nextBoundary:null,facts:{proofRefs:[{path:proofPath,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),deliveryId,changeId,runId,purpose:'isolated synthetic drift probe'}]}};
await gitBytes(root,['init','-b','main']);await gitBytes(root,['config','user.name','Fixture']);await gitBytes(root,['config','user.email','fixture@example.invalid']);
await fs.mkdir(path.join(root,base),{recursive:true});await fs.writeFile(path.join(root,'.gitattributes'),'* text=auto eol=lf\n.flowkit/runs/** -text\n.flowkit/artifacts/** -text\n');
await fs.writeFile(path.join(root,base,'action.md'),'# Isolated synthetic fixture\n');
await fs.writeFile(path.join(root,base,'context.json'),JSON.stringify(context)+'\n');await fs.writeFile(path.join(root,base,'result.json'),JSON.stringify(result)+'\n');
await gitBytes(root,['add','--','.gitattributes',base]);await gitBytes(root,['commit','-m','fixture prepared owner']);
await fs.mkdir(path.dirname(path.join(root,proofPath)),{recursive:true});await fs.writeFile(path.join(root,proofPath),bytes);await gitBytes(root,['add','--',proofPath]);
assert.equal((await readCandidateRunChain(root,deliveryId,changeId)).tip.context.lifecycleState,'prepared');
let baselineError='';await assert.rejects(requireNewManagedEvidenceBytes(root),e=>{baselineError=e.message;return /prepared chain invalid/.test(e.message);});
// Simulate uncommitted owner record drift while candidate index retains a prepared tip.
await fs.writeFile(path.join(root,base,'context.json'),JSON.stringify({...context,lifecycleState:'terminal'})+'\n');
await fs.writeFile(path.join(root,base,'result.json'),JSON.stringify({...result,authorConclusion:'PASS',nextBoundary:'review-explore'})+'\n');
await requireNewManagedEvidenceBytes(root);
const outcome=await executeScopedCheckpoint(root,'main',{kind:'create-new',paths:[proofPath],commitMessage:'fixture new proof',commitShape:null},async()=>true);
assert.equal(outcome.status,'completed');
const committedContext=JSON.parse((await gitBytes(root,['show',`HEAD:${base}/context.json`])).toString());
assert.equal(committedContext.lifecycleState,'prepared');assert.deepEqual(await gitBytes(root,['show',`HEAD:${proofPath}`]),bytes);
console.log(JSON.stringify({fixtureOnly:true,root,baselineError,worktreeLifecycle:'terminal',candidateAndCommittedLifecycle:committedContext.lifecycleState,canonicalTipRunId:(await readCandidateRunChain(root,deliveryId,changeId)).tip.context.runId,successorCount:0,outcome,proofCommitted:true}));
