import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
const root='/work/project';
const evidence=process.env.EVIDENCE_DIR;
const domain=await import(root+'/dist/domain/index.js');
const {loadManagerInstallation}=await import(root+'/dist/internal/manager-installation.js');
const deliveryId='apply-full-test-fixture';
await fs.mkdir(root+'/.flowkit');
await fs.mkdir(root+'/openspec/delivery-groups',{recursive:true});
await fs.writeFile(root+'/.flowkit/project.json',JSON.stringify({projectId:'apply-code-fixture'}));
await fs.writeFile(root+'/openspec/delivery-groups/'+deliveryId+'.yaml',`id: ${deliveryId}\ndelivery:\n  state: active\n  fullTestStatus: pending\n  finalizationStatus: pending\n`);
const ownerAuthority={ref:'owner:'+'f'.repeat(64),decision:'authorize-formal-full-test',deliveryId,sourceRef:'test:synthetic-implementation-fixture-only',scope:['delivery-full-test']};
const outcome=await domain.invokeDeliveryFullTestOperation(root,{deliveryId,ownerAuthority},loadManagerInstallation(root));
await fs.cp(root+'/.flowkit',evidence+'/linux-fixture/.flowkit',{recursive:true,errorOnExist:true,force:false});
await fs.cp(root+'/openspec',evidence+'/linux-fixture/openspec',{recursive:true,errorOnExist:true,force:false});
await fs.writeFile(evidence+'/linux-outcome.json',JSON.stringify(outcome,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify(outcome));
assert.equal(outcome.status,'terminal');
assert.equal(outcome.verdict,'passed');
const current=await domain.readCurrentDeliveryFullTest(root,deliveryId);
assert.equal(current.status,'passed',JSON.stringify(current));
await fs.mkdir(root+'/.tmp');
await fs.writeFile(root+'/.tmp/disposable','temporary');
await fs.rm(root+'/.tmp',{recursive:true});
assert.equal((await domain.readCurrentDeliveryFullTest(root,deliveryId)).status,'passed');
const fresh=spawnSync(process.execPath,['--input-type=module','-e',`import {readCurrentDeliveryFullTest} from '${root}/dist/domain/index.js'; const result=await readCurrentDeliveryFullTest('${root}','${deliveryId}'); console.log(JSON.stringify(result)); if(result.status!=='passed')process.exit(1);`],{cwd:root,encoding:'utf8'});
await fs.writeFile(evidence+'/fresh-reader.stdout.txt',fresh.stdout,{flag:'wx'});
await fs.writeFile(evidence+'/fresh-reader.stderr.txt',fresh.stderr,{flag:'wx'});
assert.equal(fresh.status,0,fresh.stderr);
await fs.writeFile(evidence+'/linux-readback.json',JSON.stringify({status:current.status,afterTmpRemoval:'passed',evidence:current.evidence},null,2)+'\n',{flag:'wx'});
