import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {parse} from 'yaml';
const proof=".flowkit/artifacts/20260908-05-lightweight-workflow-management/changes/simplify-delivery-coordination/proof/20260909-043-explore",run=".flowkit/runs/20260908-05-lightweight-workflow-management/005-simplify-delivery-coordination/20260909-043-explore",deliveryId="20260908-05-lightweight-workflow-management",changeId='simplify-delivery-coordination';
const ref=async p=>{const b=await fs.readFile(p);return {path:p,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')}};
const obs=JSON.parse(await fs.readFile(proof+'/observations.json','utf8')), command=JSON.parse(await fs.readFile(proof+'/retry.command.json','utf8'));
assert.equal(command.exitCode,0);assert.equal(obs.rows.length,7);
for(const s of obs.sources)assert.deepEqual(await ref(s.path),s);
const manifestPath='openspec/delivery-groups/'+deliveryId+'.yaml';
const manifest=parse(await fs.readFile(manifestPath,'utf8'));
const current=manifest.changes.find(c=>c.id===changeId);
assert.equal(current.state,'active');assert.equal(current.projectOrdinal,37);
assert.equal(manifest.changes.filter(c=>c.state==='active').length,1);
assert.equal(manifest.changes.find(c=>c.id==='invoke-git-at-workflow-boundaries').state,'planned');
const previous=parse(execFileSync('git',['show','HEAD:'+manifestPath],{encoding:'utf8',windowsHide:true}));
const restored=structuredClone(manifest);
restored.changes.find(c=>c.id===changeId).state='planned';
delete restored.changes.find(c=>c.id===changeId).projectOrdinal;
assert.equal(restored.ownerDecisions.pop().changeId,changeId);
assert.deepEqual(restored,previous);
const tracked=execFileSync('git',['diff','--name-only'],{encoding:'utf8',windowsHide:true}).trim().split(/\r?\n/);
assert.deepEqual(tracked,[manifestPath]);
assert.deepEqual((await fs.readdir('openspec/changes/'+changeId)).sort(),['.openspec.yaml','explore.md']);
const files=[];
async function walk(dir){for(const entry of await fs.readdir(dir,{withFileTypes:true})){const p=dir+'/'+entry.name;if(entry.isDirectory())await walk(p);else files.push(await ref(p));}}
await walk(proof);
const artifacts=[await ref(manifestPath),await ref('openspec/changes/'+changeId+'/.openspec.yaml'),await ref('openspec/changes/'+changeId+'/explore.md'),await ref(run+'/action.md'),await ref(run+'/context.json'),...files];
const result={kind:'external-orchestrator-explore-result',canonicalFlowkitRuntimeRun:false,executionMode:'independent-bootstrap',role:'author',action:'explore',deliveryId,changeId,projectOrdinal:37,runId:'20260909-043-explore',previousRunId:null,status:'terminal',authorConclusion:'PASS',meaning:'bounded Explore completed; not implementation acceptance or Reviewer approval',startedAt:JSON.parse(await fs.readFile(run+'/context.json','utf8')).startedAt,completedAt:new Date().toISOString(),proof:{observations:7,exitCode:0,platform:obs.platform,node:obs.node,initialFailure:'sandbox child process EPERM; retained, same probe retried outside sandbox'},scopeVerification:{nonTargetManifestSemanticsPreserved:true,productionTestsSkillsSpecsUnchanged:true,onlyCurrentChangeActivated:true},artifacts,limitations:obs.limits,ownerSourceRef:'owner-input:2026-09-09:activate-change:simplify-delivery-coordination:proof-explore',nextBoundary:'review-explore',reviewerVerdict:null,stop:true,notExecuted:['Propose','Apply','Review','Git mutation','D05 Full Test','Delivery Final']};
await fs.writeFile(run+'/result.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});
assert.deepEqual(JSON.parse(await fs.readFile(run+'/result.json','utf8')),result);
assert.equal((await fs.readdir(run)).length,3);
console.log(JSON.stringify({run,result:await ref(run+'/result.json'),nextBoundary:result.nextBoundary,artifacts:artifacts.length,status:'terminal'},null,2));
