import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const repo='D:/Projects/flowkit-next';
const evidence=path.dirname(fileURLToPath(import.meta.url));
const startAt=new Date().toISOString();
const {startDelivery}=await import(pathToFileURL(repo+'/src/cli/support-delivery-start.ts'));
const {runFullTest}=await import(pathToFileURL(repo+'/src/cli/support-full-test.ts'));
const {verifyGitHostAuthority}=await import(pathToFileURL(repo+'/src/domain/git-workflow-host.ts'));
const {parseSupportRequest}=await import(pathToFileURL(repo+'/src/cli/support-request.ts'));
const root=await fs.mkdtemp(path.join(repo,'.tmp/ra021-fixture-'));
const installation={root,name:'flowkit-fixture',version:'0.0.0'};
const deliveryId='review-fixture',changeId='first-change';
const owner=(letter,decision,scope)=>({ref:'owner:'+letter.repeat(64),decision,deliveryId,sourceRef:'test:review-'+letter,scope});
for(const dir of ['.flowkit','docs','openspec/delivery-groups','skills/delivery/start','skills/delivery/full-test','config/verification','.tmp'])await fs.mkdir(path.join(root,dir),{recursive:true});
await fs.writeFile(path.join(root,'.flowkit/project.json'),'{"projectId":"review-fixture"}\n');
await fs.writeFile(path.join(root,'docs/plan.md'),'# Synthetic review fixture\n');
await fs.writeFile(path.join(root,'skills/delivery/start/SKILL.md'),'# Start\n');
await fs.writeFile(path.join(root,'skills/delivery/full-test/SKILL.md'),'# Full Test\n');
const request={repositoryRoot:root,flowkitHome:root,deliveryId,ownerAuthority:owner('a','create-delivery',['delivery-start']),planningReference:{artifact:'docs/plan.md'},manifest:{createdAt:'2026-10-01',branch:'delivery/review-fixture',base:'main',goal:'original goal',changes:[{id:changeId,goal:'original change',required:true,dependsOn:[]}]}};
const initial=await startDelivery(request,installation);assert.equal(initial.status,'completed',JSON.stringify(initial));
const manifestPath=path.join(root,`openspec/delivery-groups/${deliveryId}.yaml`),before=await fs.readFile(manifestPath);
const conflicting=await startDelivery({...request,manifest:{...request.manifest,goal:'different goal',changes:[{id:'different-change',goal:'different change',required:true,dependsOn:[]}]}},installation);
const after=await fs.readFile(manifestPath);assert.ok(after.equals(before));
await fs.writeFile(path.join(root,'source.txt'),'source\n');
await fs.writeFile(path.join(root,'config/verification/full-test.json'),JSON.stringify({inputs:['source.txt'],exclude:['.flowkit','.tmp'],environment:[],checks:[{checkId:'count',program:process.execPath,args:['-e',"const fs=require('fs');const p='.tmp/count';let n=0;try{n=+fs.readFileSync(p,'utf8')}catch{}fs.writeFileSync(p,String(n+1))"],cwd:'.'}]}));
const firstId='11111111-1111-4111-8111-111111111111',secondId='22222222-2222-4222-8222-222222222222';
const first={repositoryRoot:root,deliveryId,ownerAuthority:owner('b','authorize-formal-full-test',['delivery-full-test']),attemptId:firstId,expectedCurrentAttemptId:null};
const ft1=await runFullTest(first,installation);assert.equal(ft1.status,'completed',JSON.stringify(ft1));
const ft2=await runFullTest({...first,ownerAuthority:owner('c','authorize-formal-full-test',['delivery-full-test']),attemptId:secondId,expectedCurrentAttemptId:firstId},installation);assert.equal(ft2.status,'completed',JSON.stringify(ft2));
const historicalRoot=path.join(root,`.flowkit/artifacts/${deliveryId}/full-test/${firstId}`);
const record=JSON.parse(await fs.readFile(path.join(historicalRoot,'result.json'),'utf8'));
const deletedLog=path.join(historicalRoot,'checks/count/stdout.txt');await fs.unlink(deletedLog);
const historical=await runFullTest(first,installation);
const authority={...owner('d','authorize-push',['push']),changeId};
const gitRequest={targetRoot:root,node:'change-checkpoint',deliveryId,changeId,ownerSourceRef:authority.sourceRef,expectedBranch:'delivery/review-fixture',operation:{kind:'push',localCommit:'1'.repeat(40),remote:'origin',targetRef:'refs/heads/delivery/review-fixture'}};
const parsed=parseSupportRequest('git push',{repositoryRoot:root,flowkitHome:root,deliveryId,changeId,ownerAuthority:authority,gitRequest},{repositoryRoot:root,deliveryId,changeId});
const gitApproved=await verifyGitHostAuthority(gitRequest,async()=>({request:gitRequest,checkpointAuthorization:{policyDecision:{kind:'ready-checkpoint-evaluation'},ownerAuthority:authority,deliveryId,changeId}}));
const sourcePaths=['src/cli/support-delivery-start.ts','src/cli/support-full-test.ts','src/cli/support-git.ts','src/domain/git-workflow-host.ts','src/cli/checkpoint-authorization.ts'];
const sourceHashes={};for(const p of sourcePaths)sourceHashes[p]=createHash('sha256').update(await fs.readFile(path.join(repo,p))).digest('hex');
const report={startedAt:startAt,finishedAt:new Date().toISOString(),fixtureRoot:root,synthetic:true,sourceHashes,deliveryStart:{initial:initial.status,conflicting:conflicting.status,unchangedBytes:before.equals(after),storedChanges:'first-change',requestedChanges:'different-change'},historicalFullTest:{deletedLog,replay:historical,count:await fs.readFile(path.join(root,'.tmp/count'),'utf8')},changePush:{parserAccepted:parsed.ownerAuthority.decision,policy:'ready-checkpoint-evaluation',downstreamAuthorityAccepted:gitApproved,gitMutationPerformed:false}};
await fs.writeFile(path.join(evidence,'reproduction.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify(report));
