import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const repo='D:/Projects/flowkit-next',out=path.dirname(fileURLToPath(import.meta.url));
const original=await fs.readFile(path.join(repo,'tests/unit/domain/action-archive-cli.test.ts'),'utf8');
let probe=original.replaceAll('"../../../','"file:///D:/Projects/flowkit-next/').replaceAll('"./action-context-fixture.js"','"file:///D:/Projects/flowkit-next/tests/unit/domain/action-context-fixture.ts"');
probe=probe.replace('archive finish reads trusted completed coordination after isolated preparation','reviewer probe: archive writes despite invalid Run chain');
const marker='    assert.equal(started.effect, "started");';
if(!probe.includes(marker))throw Error('probe marker missing');
probe=probe.replace(marker,marker+'\n    await mkdir(path.join(root, ".flowkit/runs/delivery-one/001-change-one/20261001-999-explore"));\n    await assert.rejects(call(["status"], "invalid-chain-query.json", base));');
const finishMarker='    const runId = started.runId as string;';
if(!probe.includes(finishMarker))throw Error('finish marker missing');
probe=probe.slice(0,probe.indexOf(finishMarker))+'  } finally {\n    await fixture.cleanup();\n  }\n});\n';
const probePath=path.join(out,'archive-chain-probe.test.ts');await fs.writeFile(probePath,probe,{flag:'wx'});
const args=['--import','tsx','--test',probePath,'tests/unit/domain/support-command-boundaries.test.ts','tests/unit/domain/support-full-test.test.ts','tests/unit/domain/support-git-checkpoint.test.ts','tests/unit/domain/support-git-integration.test.ts'];
const startedAt=new Date().toISOString();
const p=spawnSync(process.execPath,args,{cwd:repo,windowsHide:true,maxBuffer:8*1024*1024,timeout:60000});
await fs.writeFile(path.join(out,'checks.stdout.txt'),p.stdout??Buffer.alloc(0),{flag:'wx'});await fs.writeFile(path.join(out,'checks.stderr.txt'),p.stderr??Buffer.alloc(0),{flag:'wx'});
const digest=b=>createHash('sha256').update(b).digest('hex');
const report={startedAt,finishedAt:new Date().toISOString(),executable:process.execPath,args,exitCode:p.status,signal:p.signal,error:p.error?.message??null,stdoutSha256:digest(p.stdout??Buffer.alloc(0)),stderrSha256:digest(p.stderr??Buffer.alloc(0)),archiveFixtureSourceSha256:digest(original),probeMeaning:'Synthetic fixture status rejects an extra incomplete Run, but change archive still writes and reports completed; no real Reviewer verdict or actual managed OpenSpec acceptance is claimed.'};
await fs.writeFile(path.join(out,'checks.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(report));console.log((p.stdout??Buffer.alloc(0)).toString().slice(-1600));process.exitCode=p.status??1;
