import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const proof='.flowkit/artifacts/20260908-05-lightweight-workflow-management/changes/correct-project-onboarding-and-agent-entry/proof/20260911-063-explore',base=fs.mkdtempSync(path.resolve('.tmp/onboarding-039-')),target=path.join(base,'独立项目');
fs.mkdirSync(target);
fs.writeFileSync(path.join(target,'existing.txt'),'preserve existing project bytes\n');
const request=path.join(base,'query.json');
fs.writeFileSync(request,JSON.stringify({repositoryRoot:target,flowkitHome:'C:/Users/xuser/.flowkit'}));
const commands=[];
function run(id,args,expected){
 const startedAt=new Date().toISOString();
 const out=spawnSync(process.execPath,args,{cwd:target,encoding:null,maxBuffer:4*1024*1024,windowsHide:true});
 const stream=(name,b)=>{const rel=proof+'/'+id+'.'+name+'.txt';fs.writeFileSync(rel,b,{flag:'wx'});return {path:rel,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')};};
 const record={id,program:process.execPath,args,cwd:target,startedAt,finishedAt:new Date().toISOString(),exitCode:out.status,error:out.error?.message??null,stdout:stream('stdout',out.stdout??Buffer.alloc(0)),stderr:stream('stderr',out.stderr??Buffer.alloc(0))};
 commands.push(record);assert.equal(out.status,expected,JSON.stringify(record));
 return JSON.parse(out.stdout.toString());
}
const cli=path.resolve('dist/cli/entrypoint.js');
fs.mkdirSync(path.join(target,'openspec/changes'),{recursive:true});
fs.writeFileSync(path.join(target,'openspec/config.yaml'),'schema: spec-driven\n');
const idle=run('idle',[cli,'next','--input',request],0);
assert.equal(idle.status,'idle');assert.equal(idle.decision,null);
const doctor=run('doctor',[cli,'doctor','--input',request],0);
fs.mkdirSync(path.join(target,'openspec/delivery-groups'));
const mp=path.join(target,'openspec/delivery-groups/example-delivery.yaml');
fs.writeFileSync(mp,'id: example-delivery\nchanges:\n  - id: example-change\n    state: planned\n    dependsOn: []\n');
fs.writeFileSync(request,JSON.stringify({repositoryRoot:target,flowkitHome:'C:/Users/xuser/.flowkit',deliveryId:'example-delivery',changeId:'example-change'}));
const planned=run('planned',[cli,'next','--input',request],0);
assert.equal(planned.decision.kind,'blocked');assert.equal(planned.decision.reason,'change-not-active');
fs.writeFileSync(mp,'id: example-delivery\nchanges:\n  - id: example-change\n    state: active\n    dependsOn: []\nownerDecisions:\n  - ref: owner:'+ 'a'.repeat(64)+'\n    decision: activate-change\n    deliveryId: example-delivery\n    changeId: example-change\n    sourceRef: SYNTHETIC-EXPLORE-FIXTURE-NOT-OWNER-AUTHORITY\n    scope: [explore]\n');
const first=run('first-boundary',[cli,'next','--input',request],0);
assert.equal(first.decision.kind,'ready-action');assert.equal(first.decision.actionId,'explore');
assert(!fs.existsSync(path.join(target,'.flowkit/runs')));
assert(!fs.existsSync(path.join(target,'skills')));
assert.equal(fs.readFileSync(path.join(target,'existing.txt'),'utf8'),'preserve existing project bytes\n');
const files=JSON.parse(fs.readFileSync(proof+'/package-inventory/stdout.txt','utf8'))[0].files.map(f=>f.path);
assert(files.includes('README.md'));assert(files.includes('dist/cli/entrypoint.js'));
const observations={fixtureOnly:true,actualNewSession:false,realActionExecuted:false,formalFullTest:false,target,commands,outcomes:{idle,doctor,planned,first},runtimePackage:JSON.parse(fs.readFileSync('C:/Users/xuser/.flowkit/tools/openspec/1.10.0/package.json','utf8')).version,packageInventory:{files:files.length,readmeIncluded:true,rootPlanningDocuments:files.filter(f=>f.startsWith('flowkit')&&f.endsWith('.md')),developmentOrTargetFiles:files.filter(f=>/^(src|tests|\.agents|\.flowkit|openspec)\//.test(f))},decision:'现有查询与安装分根能力可复用；idle/blocked 不表示首次接入和真实工作已完成，接入说明须解释不同准备层级。'};
fs.writeFileSync(proof+'/query-observations.json',JSON.stringify(observations,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({idle:idle.status,planned:planned.decision,first:first.decision,files:files.length,actualNewSession:false,realActionExecuted:false}));
